#!/bin/bash


for ((i=0;i<10;i++))
do
sudo useradd -m user$i
done


for((i=0;i<10;i++))
do
sudo mkdir -p /home/user$i/delta
done

for((i=0;i<10;i++))
do
sudo mkdir -p /home/user$i/delta/folder{1..10}
done

for((i=0;i<10;i++))
do
for((j=1;j<=10;j++))
do
text=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
 echo $text | sudo tee /home/user$i/delta/folder$j/alpha.txt
done
done

for((i=0;i<4;i++))
do
sudo groupadd group$i
done
sudo groupadd root
sudo groupadd admin
sudo groupadd moderators 
sudo groupadd students
sudo usermod -g root user0

for((i=1;i<4;i++))
do
sudo usermod -g admin user$i
done
for((i=4;i<7;i++))
do
sudo usermod -g moderators user$i
done
for((i=7;i<10;i++))
do
sudo usermod -g students user$i
done

for((i=0;i<10;i++))
do
sudo usermod -a -G group0 user$i
done



for((i=1;i<10;i++))
do
sudo usermod -a -G group1 user$i
done

for((i=4;i<10;i++))
do
sudo usermod -a -G group2 user$i
done
for((i=7;i<10;i++))
do
sudo usermod -a -G group3 user$i
done
for((i=0;i<10;i++))
do
sudo chmod -R 707 /home/user$i
done





